version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=redis:redis
    ports:
      - 8081:8081
  produtor:
    build: ./produtor
    image: vinsdocker/produtor
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - PUBLISH_RATE=1000
  consumidor:
    build: ./consumidor
    image: vinsdocker/consumidor
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis